CREATE DATABASE recipe_db; --remove for docker

\c recipe_db -- remove for docker

CREATE TABLE Recipe (
    recipe_id INT PRIMARY KEY,
    recipe_name TEXT NOT NULL,
    ingredient_list TEXT,  -- Dictionary of ingredients with their quantities and importance as values
    preparation_time INT,  -- Time in minutes
    serving_size INT,  -- Number of servings
    dietary_requirement TEXT CHECK (dietary_requirement IN ('veg', 'non-veg')),
    instructions TEXT 
);

CREATE TABLE Ingredient (
    ingredient_id INT PRIMARY KEY,
    ingredient_name TEXT NOT NULL,
    alternatives_list TEXT 
);

CREATE TABLE UserInventory (
    user_id INT NOT NULL,
    fridge_id INT NOT NULL,
    ingredients TEXT NOT NULL, 
    PRIMARY KEY (user_id)
);

INSERT INTO Recipe (recipe_id, recipe_name, ingredient_list, preparation_time, serving_size, dietary_requirement, instructions)
VALUES 
(1, 'Mediterranean Tomato Cucumber Salad', 
    '{101: ["200g", "core"], 102: ["150g", "core"], 103: ["50g", "secondary"], 302: ["30ml", "secondary"]}', 
    15, 2, 'veg', 
    '1. Wash and chop tomatoes and cucumber into bite-sized pieces. 2. Thinly slice red onion. 3. Mix vegetables in a bowl. 4. Drizzle with olive oil. 5. Season with salt and pepper. 6. Serve chilled.'),

(2, 'Coconut Chicken Curry', 
    '{201: ["500g", "core"], 202: ["20g", "core"], 203: ["400ml", "core"], 
      204: ["30g", "secondary"], 205: ["10g", "secondary"], 
      302: ["30ml", "secondary"]}', 
    60, 4, 'non-veg', 
    '1. Chop chicken into cubes. 2. Sauté ginger and garlic in olive oil. 3. Add chicken and brown. 4. Stir in curry powder. 5. Pour coconut milk and simmer for 40 minutes. 6. Serve hot with rice.'),

(3, 'Vegetable Medley Roast', 
    '{301: ["400g", "core"], 302: ["50ml", "core"], 
      204: ["10g", "secondary"], 205: ["5g", "secondary"]}', 
    45, 3, 'veg', 
    '1. Chop mixed vegetables into uniform pieces. 2. Toss with olive oil and minced garlic. 3. Sprinkle curry powder. 4. Roast in oven at 200°C for 30 minutes. 5. Serve hot as a side dish.'),

(4, 'Classic Egg Toast', 
    '{401: ["2", "core"], 402: ["2", "core"], 302: ["10ml", "secondary"], 
      205: ["2", "optional"]}', 
    10, 1, 'non-veg', 
    '1. Heat olive oil in a pan. 2. Toast bread. 3. Fry eggs sunny-side up. 4. Place eggs on toast. 5. Sprinkle minced garlic if desired. 6. Season with salt and pepper.'),

(5, 'Banana Honey Smoothie', 
    '{501: ["200g", "core"], 
      502: ["150ml", "core"], 
      503: ["30ml", "secondary"], 
      302: ["10ml", "optional"]}', 
    10, 2, 'veg', 
    '1. Peel and chop banana. 2. Blend banana with Greek yogurt. 3. Add honey for sweetness. 4. Optional: Add a drop of olive oil for richness. 5. Blend until smooth. 6. Serve chilled.'),

(6, 'Lemon Dill Salmon', 
    '{601: ["600g", "core"], 
      602: ["30ml", "secondary"], 
      603: ["10g", "secondary"], 
      302: ["20ml", "core"]}', 
    40, 4, 'non-veg', 
    '1. Preheat oven to 180°C. 2. Place salmon on baking tray. 3. Drizzle with olive oil. 4. Squeeze lemon juice over salmon. 5. Sprinkle chopped fresh dill. 6. Bake for 20-25 minutes. 7. Serve hot with lemon wedges.'),

(7, 'Spinach and Tofu Stir Fry', 
    '{702: ["300g", "core"], 
      801: ["200g", "core"], 
      802: ["100g", "secondary"], 
      1101: ["10g", "secondary"], 
      1301: ["30ml", "secondary"]}', 
    25, 3, 'veg', 
    '1. Press and cube tofu. 2. Chop spinach and bell peppers. 3. Heat oil in a wok. 4. Stir-fry tofu until golden. 5. Add spinach and peppers. 6. Season with soy sauce and fresh basil. 7. Serve hot.'),

(8, 'Mediterranean Lamb with Roasted Vegetables', 
    '{704: ["500g", "core"], 
      803: ["250g", "core"], 
      804: ["200g", "core"], 
      805: ["150g", "secondary"], 
      1102: ["15g", "secondary"], 
      1104: ["5g", "secondary"]}', 
    70, 4, 'non-veg', 
    '1. Marinate lamb with paprika and herbs. 2. Chop eggplant, zucchini, and carrots. 3. Roast vegetables with olive oil. 4. Grill lamb to desired doneness. 5. Garnish with fresh cilantro. 6. Serve with roasted vegetables.'),

(9, 'Avocado and Shrimp Rice Bowl', 
    '{703: ["250g", "core"], 
      1203: ["200g", "core"], 
      901: ["150g", "core"], 
      802: ["100g", "secondary"], 
      1302: ["20ml", "secondary"], 
      1103: ["10g", "optional"]}', 
    30, 2, 'non-veg', 
    '1. Cook rice. 2. Sauté shrimp with vinegar. 3. Slice avocado and bell peppers. 4. Assemble rice bowl. 5. Top with fresh mint. 6. Drizzle with dressing.'),

(10, 'Vegetarian Potato and Cheese Bake', 
    '{903: ["400g", "core"], 
      1001: ["200g", "core"], 
      801: ["150g", "secondary"], 
      1105: ["5g", "secondary"], 
      1402: ["50g", "optional"]}', 
    55, 3, 'veg', 
    '1. Slice potatoes. 2. Layer with spinach and cheese. 3. Sprinkle cumin. 4. Optional: Add flour for thickening. 5. Bake until golden and crispy. 6. Let rest for 10 minutes before serving.'),

(11, 'Apple Cinnamon Oatmeal', 
    '{1201: ["200g", "core"], 
      1401: ["30g", "secondary"], 
      1403: ["10ml", "secondary"], 
      1502: ["15g", "optional"]}', 
    20, 2, 'veg', 
    '1. Dice apples. 2. Cook with sugar and vanilla. 3. Add chia seeds if desired. 4. Serve warm. 5. Can be topped with additional fruits or nuts.'),

(12, 'Beef and Vegetable Pasta', 
    '{701: ["400g", "core"], 
      902: ["250g", "core"], 
      802: ["150g", "secondary"], 
      804: ["100g", "secondary"], 
      1303: ["20g", "optional"]}', 
    45, 4, 'non-veg', 
    '1. Brown beef in pan. 2. Cook pasta. 3. Sauté bell peppers and zucchini. 4. Mix all ingredients. 5. Optional: Add mustard for extra flavor. 6. Garnish and serve hot.'),

(13, 'Zucchini Noodle Shrimp Alfredo', 
    '{703: ["300g", "core"], 
      804: ["400g", "core"], 
      1003: ["200ml", "core"], 
      1001: ["100g", "secondary"], 
      1101: ["15g", "secondary"]}', 
    35, 2, 'non-veg', 
    '1. Spiralize zucchini into noodles. 2. Sauté shrimp until pink. 3. Make cream sauce with cheese. 4. Combine shrimp, zucchini noodles, and sauce. 5. Garnish with fresh basil. 6. Serve immediately.'),

(14, 'Spicy Tofu and Bell Pepper Curry', 
    '{702: ["350g", "core"], 
      802: ["200g", "core"], 
      203: ["300ml", "core"], 
      1104: ["10g", "secondary"], 
      1105: ["5g", "secondary"], 
      1102: ["15g", "optional"]}', 
    40, 3, 'veg', 
    '1. Press and cube tofu. 2. Chop bell peppers. 3. Create curry base with coconut milk. 4. Add paprika and cumin. 5. Simmer tofu and peppers. 6. Garnish with fresh cilantro. 7. Serve with rice.'),

(15, 'Mediterranean Lamb Salad', 
    '{704: ["400g", "core"], 
      801: ["150g", "core"], 
      102: ["100g", "core"], 
      103: ["50g", "secondary"], 
      1302: ["30ml", "secondary"], 
      1101: ["10g", "optional"]}', 
    45, 4, 'non-veg', 
    '1. Grill lamb to medium rare. 2. Slice thinly. 3. Prepare bed of spinach and cucumber. 4. Add red onions. 5. Dress with vinegar. 6. Top with fresh basil. 7. Serve chilled or at room temperature.'),

(16, 'Loaded Vegetable Potato Skins', 
    '{903: ["500g", "core"], 
      1001: ["150g", "core"], 
      802: ["100g", "secondary"], 
      801: ["100g", "secondary"], 
      1503: ["50g", "optional"]}', 
    60, 4, 'veg', 
    '1. Bake potatoes until soft. 2. Scoop out potato centers. 3. Fill with cheese, bell peppers, and spinach. 4. Top with chopped peanuts if desired. 5. Bake until cheese melts. 6. Serve hot.'),

(17, 'Tropical Shrimp Coconut Rice', 
    '{703: ["300g", "core"], 
      901: ["200g", "core"], 
      203: ["250ml", "core"], 
      1202: ["150g", "secondary"], 
      1103: ["10g", "optional"]}', 
    35, 3, 'non-veg', 
    '1. Cook rice in coconut milk. 2. Sauté shrimp. 3. Segment oranges. 4. Mix shrimp with rice. 5. Garnish with fresh mint. 6. Serve with orange segments.'),

(18, 'Vegan Lentil and Vegetable Stew', 
    '{702: ["250g", "core"], 
      801: ["200g", "core"], 
      804: ["150g", "core"], 
      1105: ["5g", "secondary"], 
      1104: ["5g", "secondary"], 
      1102: ["15g", "optional"]}', 
    50, 4, 'veg', 
    '1. Crumble tofu. 2. Chop spinach and zucchini. 3. Create stew base with cumin and paprika. 4. Slow cook all ingredients. 5. Garnish with fresh cilantro. 6. Serve with crusty bread.'),

(19, 'Apple Almond Breakfast Parfait', 
    '{1201: ["200g", "core"], 
      1501: ["100g", "core"], 
      1002: ["250ml", "core"], 
      1401: ["30g", "secondary"], 
      1502: ["15g", "optional"]}', 
    20, 2, 'veg', 
    '1. Dice apples. 2. Layer with almonds and milk. 3. Sprinkle sugar. 4. Add chia seeds if desired. 5. Chill for 10 minutes. 6. Serve cold.'),

(20, 'Mediterranean Beef and Quinoa Pasta', 
    '{701: ["400g", "core"], 
      902: ["250g", "core"], 
      803: ["150g", "secondary"], 
      1601: ["100g", "secondary"], 
      1103: ["10g", "optional"], 
      1303: ["20g", "secondary"]}', 
    45, 4, 'non-veg', 
    '1. Brown beef in pan. 2. Cook pasta and quinoa separately. 3. Sauté eggplant. 4. Mix beef, pasta, quinoa, and eggplant. 5. Add mustard. 6. Garnish with mint. 7. Serve hot.'),

(21, 'Protein-Packed Chickpea Power Bowl', 
    '{1603: ["250g", "core"], 
      903: ["200g", "core"], 
      801: ["150g", "core"], 
      1605: ["30ml", "secondary"], 
      1103: ["10g", "optional"], 
      302: ["20ml", "core"]}', 
    40, 3, 'veg', 
    '1. Roast sweet potatoes. 2. Prepare chickpeas. 3. Sauté kale in olive oil. 4. Create tahini dressing. 5. Layer ingredients in a bowl. 6. Garnish with mint. 7. Serve at room temperature.'),

(22, 'Spicy Mediterranean Roasted Vegetable and Lentil Medley', 
    '{802: ["250g", "core"], 
      1602: ["200g", "core"], 
      1202: ["150g", "secondary"], 
      302: ["40ml", "core"], 
      1604: ["10g", "secondary"], 
      1104: ["10g", "secondary"], 
      1105: ["10g", "secondary"]}', 
    55, 4, 'veg', 
    '1. Roast cauliflower and bell peppers. 2. Cook lentils. 3. Segment oranges. 4. Toss vegetables with olive oil. 5. Sprinkle with paprika and cumin. 6. Top with nutritional yeast. 7. Garnish with orange segments. 8. Serve hot.'),

(23, 'Coconut Seitan Vegetable Curry', 
    '{702: ["350g", "core"], 
      203: ["300ml", "core"], 
      804: ["200g", "core"], 
      1503: ["30g", "secondary"], 
      1103: ["10g", "optional"], 
      302: ["25ml", "secondary"]}', 
    50, 3, 'veg', 
    '1. Prepare seitan. 2. Roast butternut squash. 3. Create curry base with coconut milk. 4. Add seitan and vegetables. 5. Simmer until flavors meld. 6. Garnish with peanuts and mint. 7. Serve with rice.'),

(24, 'Mediterranean Halloumi and Roasted Vegetable Salad', 
    '{1001: ["250g", "core"], 
      1202: ["150g", "secondary"], 
      102: ["100g", "core"], 
      103: ["50g", "secondary"], 
      302: ["30ml", "core"], 
      1302: ["20ml", "secondary"]}', 
    35, 2, 'veg', 
    '1. Grill halloumi. 2. Roast pumpkin. 3. Prepare cucumber and red onion. 4. Add pomegranate seeds. 5. Create orange-infused dressing. 6. Layer ingredients. 7. Serve chilled.'),

(25, 'Spicy Tempeh and Bok Choy Stir Fry', 
    '{702: ["250g", "core"], 
      1201: ["200g", "core"], 
      804: ["150g", "core"], 
      1301: ["30ml", "secondary"], 
      602: ["20ml", "secondary"], 
      1101: ["10g", "optional"]}', 
    30, 3, 'veg', 
    '1. Press and marinate tempeh. 2. Prepare water chestnuts. 3. Chop bok choy. 4. Heat soy sauce and lime juice in wok. 5. Stir-fry tempeh until golden. 6. Add vegetables. 7. Garnish with Thai basil. 8. Serve immediately.'),

(26, 'Protein-Packed Black Bean and Avocado Bowl', 
    '{1603: ["300g", "core"], 
      1203: ["200g", "core"], 
      902: ["150g", "core"], 
      302: ["40ml", "core"], 
      1102: ["5g", "optional"]}', 
    40, 3, 'veg', 
    '1. Prepare black beans. 2. Roast corn. 3. Slice avocado. 4. Mix ingredients in a bowl. 5. Dress with lime juice and olive oil. 6. Garnish with cilantro and pumpkin seeds. 7. Serve at room temperature.'),

(27, 'Mediterranean Feta and Vegetable Feast', 
    '{1001: ["250g", "core"], 
      102: ["200g", "core"], 
      801: ["150g", "secondary"], 
      302: ["30ml", "core"], 
      1302: ["20ml", "secondary"], 
      1102: ["10g", "optional"]}', 
    35, 2, 'veg', 
    '1. Crumble feta cheese. 2. Roast artichoke hearts. 3. Add sun-dried tomatoes. 4. Chop cucumber and spinach. 5. Dress with balsamic vinegar. 6. Sprinkle dried oregano. 7. Serve chilled or at room temperature.'),

(28, 'Spicy Tempeh and Butternut Squash Curry', 
    '{702: ["350g", "core"], 
      203: ["300ml", "core"], 
      804: ["250g", "core"], 
      1503: ["40g", "secondary"], 
      1102: ["5g", "optional"], 
      302: ["25ml", "secondary"]}', 
    55, 4, 'veg', 
    '1. Prepare tempeh. 2. Roast butternut squash. 3. Create curry base with coconut milk. 4. Add tempeh and squash. 5. Top with roasted cashews. 6. Garnish with pomegranate seeds. 7. Serve with steamed rice.'),

(29, 'Roasted Vegetable and Tempeh Medley', 
    '{702: ["300g", "core"], 
      805: ["200g", "core"], 
      804: ["150g", "core"], 
      302: ["35ml", "core"], 
      1104: ["5g", "secondary"], 
      1105: ["5g", "secondary"], 
      1102: ["10g", "optional"]}', 
    50, 3, 'veg', 
    '1. Press and marinate tempeh. 2. Roast beetroot and fennel. 3. Chop zucchini and carrots. 4. Toss with olive oil and fresh rosemary. 5. Sprinkle paprika and cumin. 6. Drizzle with maple syrup. 7. Serve hot as a main course.'),

(30, 'Protein-Rich Seitan and Vegetable Stir Fry', 
    '{702: ["250g", "core"], 
      1201: ["200g", "core"], 
      804: ["150g", "core"], 
      1301: ["30ml", "secondary"], 
      202: ["20g", "secondary"], 
      1101: ["10g", "optional"]}', 
    35, 2, 'veg', 
    '1. Prepare seitan. 2. Add water chestnuts. 3. Slice purple cabbage and zucchini. 4. Heat soy sauce in wok. 5. Stir-fry with fresh ginger. 6. Garnish with toasted sesame seeds. 7. Serve immediately.');

INSERT INTO Ingredient (ingredient_id, ingredient_name, alternatives_list)
VALUES
(101, 'Tomato', '["cherry tomato", "plum tomato"]'),
(102, 'Cucumber', '["english cucumber", "persian cucumber"]'),
(103, 'Red Onion', '["sweet onion", "white onion"]'),
(201, 'Chicken Breast', '["chicken thigh", "turkey breast"]'),
(202, 'Ginger', '["ginger paste", "minced ginger"]'),
(203, 'Coconut Milk', '["cream", "almond milk"]'),
(204, 'Curry Powder', '["garam masala", "turmeric"]'),
(205, 'Garlic', '["garlic paste", "dried garlic"]'),
(301, 'Mixed Vegetables', '["frozen vegetables", "seasonal vegetables"]'),
(302, 'Olive Oil', '["vegetable oil", "canola oil"]'),
(401, 'Bread', '["whole wheat bread", "sourdough"]'),
(402, 'Egg', '["egg whites", "vegan egg substitute"]'),
(501, 'Banana', '["frozen banana", "plantain"]'),
(502, 'Greek Yogurt', '["regular yogurt", "plant-based yogurt"]'),
(503, 'Honey', '["agave syrup", "maple syrup"]'),
(601, 'Salmon', '["trout", "tilapia"]'),
(602, 'Lemon', '["lime", "preserved lemon"]'),
(603, 'Dill', '["dried dill", "parsley"]'),
(701, 'Beef', '["ground beef", "steak", "sirloin"]'),
(702, 'Tofu', '["tempeh", "seitan", "plant-based protein"]'),
(703, 'Shrimp', '["prawns", "crab", "imitation crab"]'),
(704, 'Lamb', '["goat meat", "mutton"]'),
(801, 'Spinach', '["kale", "swiss chard", "collard greens"]'),
(802, 'Bell Pepper', '["capsicum", "paprika", "chili pepper"]'),
(803, 'Eggplant', '["aubergine", "brinjal"]'),
(804, 'Zucchini', '["courgette", "summer squash"]'),
(805, 'Carrot', '["baby carrot", "rainbow carrot"]'),
(901, 'Rice', '["basmati rice", "brown rice", "jasmine rice"]'),
(902, 'Pasta', '["spaghetti", "penne", "gluten-free pasta"]'),
(903, 'Potato', '["sweet potato", "yam", "fingerling potato"]'),
(1001, 'Cheese', '["cheddar", "mozzarella", "vegan cheese"]'),
(1002, 'Milk', '["almond milk", "soy milk", "oat milk"]'),
(1003, 'Cream', '["heavy cream", "light cream", "coconut cream"]'),
(1101, 'Basil', '["fresh basil", "dried basil", "thai basil"]'),
(1102, 'Cilantro', '["coriander leaves", "chinese parsley"]'),
(1103, 'Mint', '["peppermint", "spearmint"]'),
(1104, 'Paprika', '["smoked paprika", "hot paprika"]'),
(1105, 'Cumin', '["ground cumin", "whole cumin seeds"]'),
(1201, 'Apple', '["green apple", "red apple", "cooking apple"]'),
(1202, 'Orange', '["mandarin", "clementine", "blood orange"]'),
(1203, 'Avocado', '["hass avocado", "fuerte avocado"]'),
(1301, 'Soy Sauce', '["tamari", "light soy sauce", "dark soy sauce"]'),
(1302, 'Vinegar', '["apple cider vinegar", "rice vinegar", "balsamic vinegar"]'),
(1303, 'Mustard', '["dijon mustard", "whole grain mustard", "yellow mustard"]'),
(1401, 'Sugar', '["brown sugar", "raw sugar", "coconut sugar"]'),
(1402, 'Flour', '["wheat flour", "almond flour", "gluten-free flour"]'),
(1403, 'Vanilla Extract', '["vanilla bean", "vanilla paste"]'),
(1501, 'Almonds', '["sliced almonds", "almond flour", "roasted almonds"]'),
(1502, 'Chia Seeds', '["ground chia", "whole chia seeds"]'),
(1503, 'Peanut', '["roasted peanuts", "peanut butter"]'),
(1601, 'Quinoa', '["red quinoa", "white quinoa", "black quinoa"]'),
(1602, 'Lentils', '["red lentils", "green lentils", "brown lentils"]'),
(1603, 'Chickpeas', '["canned chickpeas", "dried chickpeas", "roasted chickpeas"]'),
(1604, 'Nutritional Yeast', '["fortified nutritional yeast", "non-fortified nutritional yeast"]'),
(1605, 'Tahini', '["light tahini", "dark tahini", "whole sesame tahini"]');

INSERT INTO UserInventory (user_id, fridge_id, ingredients)
VALUES 
(1, 1, '{101: "250g", 102: "200g", 103: "100g", 302: "50ml", 602: "30ml", 1102: "10g"}'), 
(2, 1, '{201: "500g", 202: "20g", 203: "400ml", 204: "30g", 205: "10g", 302: "30ml"}'), 
(3, 2, '{702: "350g", 801: "200g", 802: "200g", 203: "300ml", 1104: "10g", 1105: "5g", 302: "25ml"}'), 
(4, 2, '{401: "2", 402: "2", 302: "10ml", 205: "2", 1001: "100g", 903: "200g"}'), 
(5, 3, '{501: "200g", 502: "150ml", 503: "30ml", 302: "10ml", 1201: "200g", 1401: "30g", 1403: "10ml"}'), 
(6, 3, '{601: "600g", 602: "30ml", 603: "10g", 302: "20ml", 1102: "10g", 703: "250g", 901: "200g"}'), 
(7, 4, '{702: "300g", 801: "200g", 802: "150g", 1101: "10g", 1301: "30ml", 1203: "200g", 902: "150g"}'), 
(8, 4, '{704: "500g", 803: "250g", 804: "200g", 805: "150g", 1102: "15g", 1104: "5g", 1001: "150g", 302: "30ml"}');