name: Run Tests

on:
  workflow_run:
    workflows: ["Build and Dependency Setup"]
    types:
      - completed

  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: SEPP
          POSTGRES_PASSWORD: prototype
          POSTGRES_DB: recipe_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U SEPP -d recipe_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Optional: Download artifacts from the Build workflow
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./build_artifacts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ./build_artifacts/pip_cache

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U SEPP -d recipe_db; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Tests
        run: |
          pytest test.py --junitxml=pytest-results.xml
        env:
          DATABASE_URL: postgres://SEPP:prototype@localhost:5432/recipe_db

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            pytest-results.xml
            *.log
          retention-days: 7
